/**
 * Object representing a tile map generated by Tiled Map Editor.
 * Parses the .tmx file content and facilitates the access to its data.
 * @class tmxMap
 */
FM.tmxMap = function () {
    "use strict";
    var that = {},
        /**
         * The map.
         */
        map = null;
    /**
     * Version number of the tile map.
     */
    that.version = "unknown";
    /**
     * Whether the tile map is orthogonal or isometric.
     */
    that.orientation = "orthogonal";
    /**
     * Number of tiles along the x-axis.
     */
    that.width = 0;
    /**
     * Number of tiles along the y-axis.
     */
    that.height = 0;
    /**
     * Width of a tile.
     */
    that.tileWidth = 0;
    /**
     * Height of a tile.
     */
    that.tileHeight = 0;
    /**
     * Custom properties of the map.
     */
    that.properties = null;
    /**
     * The different layers of the map.
     */
    that.layers = [];
    /**
     * The different tile sets of the tile map.
     */
    that.tileSets = [];
    /**
     * The different groups of objects defined in the tile map.
     */
    that.objectGroups = [];

    /**
     * Load the tile map and create javascript objects.
     * @param {string} source the string of the .tmx file content.
     */
    that.load = function (source) {
        var xmlDoc, parser;
        if (window.DOMParser) {
            parser = new DOMParser();
            xmlDoc = parser.parseFromString(source, "text/xml");
        } else {
            xmlDoc = new ActiveXObject("Microsoft.XMLDOM");
            xmlDoc.async = false;
            xmlDoc.loadXML(source); 
        }

        map = xmlDoc.getElementsByTagName("map")[0];
        that.version = map.getAttribute("version") || "unknown";
        that.orientation = map.getAttribute("orientation") || "orthogonal";
        that.width = parseInt(map.getAttribute("width"));
        that.height = parseInt(map.getAttribute("height"));
        that.tileWidth = parseInt(map.getAttribute("tilewidth"));
        that.tileHeight = parseInt(map.getAttribute("tileheight"));

        var properties = map.getElementsByTagName("properties")[0],
            tileSets = map.getElementsByTagName("tileset"),
            layers = map.getElementsByTagName("layer"),
            objectGroups = map.getElementsByTagName("objectgroup"),
            property,
            tileSet,
            layer,
            objectGroup,
            i;
        //Load properties
        if (properties) {
            for (i = 0; i < properties.childNodes.length; i++) {
                if (properties.hasChildNodes() === true) {
                    property = properties.childNodes[i];
                    if (property.nodeType === 1) {
                        if (that.properties) {
                            that.properties.add(property);
                        } else {
                            that.properties = FM.tmxPropertySet();
                            that.properties.add(property);
                        }
                    }
                }
            }
        }
        //Load tilesets
        if (tileSets) {
            for (i = 0; i < tileSets.length; i++) {
                tileSet = tileSets[i];
                that.tileSets[tileSet.getAttribute("name")] = FM.tmxTileSet();
                that.tileSets[tileSet.getAttribute("name")].load(tileSet, that);
            }
        }
        //Load layer
        if (layers) {
            for (i = 0; i < layers.length; i++) {
                layer = layers[i];
                that.layers[layer.getAttribute("name")] = FM.tmxLayer();
                that.layers[layer.getAttribute("name")].load(layer, that);
            }
        }
        //Load object group
        if (objectGroups) {
            for (i = 0; i < objectGroups.length; i++) {
                objectGroup = objectGroups[i];
                that.objectGroups[objectGroup.getAttribute("name")] = FM.tmxObjectGroup();
                that.objectGroups[objectGroup.getAttribute("name")].load(objectGroup, that);
            }
        }
    };

    /**
     * Retrieve a tile set from its name.
     * @param {string} name the name of the tile set to retrieve.
     * @returns {tmxTileSet} tile set corresponding to the given name.
     */
    that.getTileSet = function (name) {
        return that.tileSets[name];
    };

    /**
     * Retrieve a layer from its name.
     * @param {string} name name of the layer to retrieve.
     * @returns {tmxLayer} layer corresponding of the specified name.
     */
    that.getLayer = function (name) {
        return that.layers[name];
    };

    /**
     * Retrieve an object group from its name.
     * @param {string} name name of the group to retrieve.
     * @returns {tmxGroup} group of objects matching the given name.
     */
    that.getObjectGroup = function (name) {
        return that.objectGroups[name];
    };

    /**
     * Retrieve the tile set matching the specified id.
     * Works only after TmxTileSet has been initialized with an image...
     * @param {int} gid the gid of the tileset to retrieve.
     * @returns {tmxTileSet} the tile set matching the gid provided, or null if none is found.
     */
    that.getGidOwner = function (gid) {
        var last = null;
        for (var tileSet in that.tileSets)
        {
            if(tileSet.hasGid(gid))
                return tileSet;
        }
        return null;
    };

    return that;
};